excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - .tuist-bin
  - Project.swift
  - Derived

disabled_rules:
  - private_over_fileprivate

function_body_length:
  - 20

cyclomatic_complexity:
  - 5

line_length: 250

identifier_name:
  excluded: # excluded via string array
    - id
    - URL
